<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delybot">

    <!-- BOX PROPERTIES -->
    <xacro:property name="box_width" value="0.45" />
    <xacro:property name="box_depth" value="0.63" />
    <xacro:property name="box_height" value="0.54" />
    <xacro:property name="box_mass" value="42" /> 

    <!-- WHEEL PROPERTIES -->
    <xacro:property name="wheel_radius" value="0.11" />
    <xacro:property name="wheel_width" value="0.08" />
    <xacro:property name="wheel_offset_from_bottom_chassis" value="0.0" />
    <xacro:property name="wheel_offset_from_front_chassis" value="0.0" />
    <xacro:property name="wheel_offset_from_back_chassis" value="0.0" />
    <xacro:property name="wheel_mass" value="0.5" />

    <!-- MACRO DEFINITION -->

    <!-- DEFAULT INERTIA MACRO -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- WHEEL MACRO -->
    <xacro:macro name="wheel_macro" params="position x y">
        <link name="${position}_wheel">
            <visual>
                <material name="black"/>
                <origin xyz="0.0 0.0 0.0" rpy="1.57075 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="1.57075 0.0 0.0"/>
                <geometry>
                   <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
               </geometry>
            </collision>
            <xacro:default_inertial mass="${wheel_mass}"/>
        </link>

        <!-- JOINT DEFINITION -->

        <joint name="${position}_wheel_joint" type="continuous">
            <origin xyz="${x} ${y} -${box_height/2 - wheel_offset_from_bottom_chassis}" rpy="0.0 0.0 0.0"/>
            <parent link="base_box"/>
            <child link="${position}_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
            <!-- <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/> -->
        </joint>

        <gazebo reference="${position}_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <!-- TRASMISSION DEFINITION -->

        <transmission name="${position}_wheel_joint_tran">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${position}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${position}_wheel_joint_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- MATERIAL DEFINITIONS -->

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link"/>


    <!-- BASE BOX -->

    <link name="base_box">
        <visual>
            <material name="white"/>
            <geometry>
                <box size="${box_depth} ${box_width} ${box_height}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${box_depth} ${box_width} ${box_height}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${box_mass}"/>
    </link>

    <gazebo reference="base_box">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- BOX - BASE JOINT -->

    <joint name="box_to_base_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_box"/>
    </joint>

    <!-- LEFT FRONT WHEEL -->

    <xacro:wheel_macro position="left_front" x="${box_depth/2 - wheel_offset_from_front_chassis}" y="${box_width/2 + wheel_width/2}"/>

    <!-- LEFT CENTER WHEEL -->

    <xacro:wheel_macro position="left_center" x="0" y="${box_width/2 + wheel_width/2}"/>

    <!-- LEFT BACK WHEEL -->

    <xacro:wheel_macro position="left_back" x="${-box_depth/2 + wheel_offset_from_front_chassis}" y="${box_width/2 + wheel_width/2}"/>

    <!-- RIGHT FRONT WHEEL -->

    <xacro:wheel_macro position="right_front" x="${box_depth/2 - wheel_offset_from_front_chassis}" y="${-box_width/2 - wheel_width/2}"/>

    <!-- RIGHT CENTER WHEEL -->

    <xacro:wheel_macro position="right_center" x="0" y="${-box_width/2 - wheel_width/2}"/>

    <!-- RIGHT BACK WHEEL -->

    <xacro:wheel_macro position="right_back" x="${-box_depth/2 + wheel_offset_from_front_chassis}" y="${-box_width/2 - wheel_width/2}"/>


    <!-- GAZEBO PLUGIN -->

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>

</robot>
